name: PR Size Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  label_pr_size:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add PR Size Label
        uses: pascalgn/size-label-action@56b489b027932ec0cf60438a1a5f1a19c8fc71ff # v0.5.7
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "size/XS",
              "20": "size/S",
              "50": "size/M",
              "200": "size/L",
              "500": "size/XL",
              "1000": "size/XXL"
            }
